name: Deploy to github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to github pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0"
          gleam-version: "1.8.0"
          rebar3-version: "3"
      - name: Install dependencies
        run: gleam deps download
      - name: Build app
        run: gleam run -m lustre/dev build app --minify
      - name: Copy output to dist
        run: |
          mkdir -p dist
          cp index.html dist/index.html
          cp src/components/scrollbar.css dist/scrollbar.css
          cp -r static dist/static
          cp -r priv dist/priv
      - name: Update path in index.html to use minified app
        run: |
          sed -i 's|priv/static/personal.mjs|site/priv/static/personal.min.mjs|' dist/index.html
          sed -i 's|priv/static/personal.css|priv/static/personal.min.css|' dist/index.html
          sed -i 's|src/components/scrollbar.css|scrollbar.css|' dist/index.html
      - name: Setup pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist"
      - name: Deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4